version: '3.8'
services:
  api-terceiro:
    container_name: api-terceiro-periodo
    image: brennocosta/api-terceiro-periodo:latest
    ports:
      - "8080:8080"
    networks:
      - rede1
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/terceiro_periodo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    image: postgres:latest
    container_name: postgres
    networks:
      - rede1
    environment:
      - POSTGRES_DB=terceiro_periodo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dados-db:/var/lib/postgresql/data

networks:
  rede1:

volumes:
  dados-db:
